### ISSUE TITLE
Implement Isomorphic fetch so it works for browsers 

### ISSUE THREAD

**Issue by deadcoder0904** [jacktuck/unfurl#38]
Hey, thank you for this wonderful package.

I know this is a Node JS package but can it be used from the frontend like React?

I'm currently making a Chrome extension where I need to get metadata of any site specified so I did this -

```javascript
import unfurl from "unfurl";

_fetchMeta = async () => {
    try {
      let result = await unfurl("https://akshaykadam.me");
      console.log("result", result);
      alert(result);
    } catch (e) {
      console.error("e", e);
    }
};
```

But I get this error - 

```
Failed to load https://akshaykadam.me/: No 'Access-Control-Allow-Origin' header is present on the 
requested resource. Origin 'http://localhost:3000' is therefore not allowed access. If an opaque 
response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS 
disabled.

e TypeError: Failed to fetch
```

In Chrome Extension, it can be removed by adding `"permissions": ["<all_urls>"]` so I did that but still doesn't work. 

It should work as written here 👇
`Source:` Find `Cross-Domain from Chrome Extensions` in [CORS tutorial](https://www.html5rocks.com/en/tutorials/cors/)

I also tried running it as a Web App but still same error. So my question is it possible to do this from Frontend?

**Comment by jacktuck** [comment]
Hi @deadcoder0904 👋 

Thanks for your interest in the package!

I've never actually tested how it'd work in the browser but the last time i considered supporting browsers I didn't think it'd be useful because of CORS. But i didn't consider the possibility of using it within a chrome extension which can bypass CORS as you've mentioned. A very cool use case!

As for why you get that CORS issue though despite adding `permissions` to your manifest, I'm not too sure - are you able to share the code or a reproduction?

**Comment by deadcoder0904** [comment]
Hey @jacktuck I have created a repro & given the instructions in the README & in the Chrome Extension itself about installing the extension to showing the error. Let me know if you have any questions :)

**Comment by deadcoder0904** [comment]
And the most weird part is it gives plain old HTML with just an `axios` request

```js
axios
      .get("https://framer.com/")
      .then(console.log)
      .catch(console.error);
```

**Comment by deadcoder0904** [comment]
Oops I forgot to link to the repo 🤣👉 https://github.com/deadcoder0904/unfurl-chrome-extension-bug

**Comment by deadcoder0904** [comment]
Also I forgot to mention that its not a CORS issue as stated in the error because I've read a lot of articles that state that Chrome Extension can request any Cross Origin URL without any issues. Let me know if you need any help though :)

**Comment by deadcoder0904** [comment]
I think the issue must be [node-fetch](https://github.com/bitinn/node-fetch) but I'm not so sure. Although you can try changing it to [cross-fetch](https://github.com/lquixada/cross-fetch) or [isomorphic-fetch](https://github.com/matthew-andrews/isomorphic-fetch)

Sorry Idk TypeScript otherwise I would've sent a PR

**Comment by deadcoder0904** [comment]
Sorry for so much spam 🙏

But I think I found the error [here](https://github.com/bitinn/node-fetch/blob/master/LIMITS.md) in the first point

> Topics such as Cross-Origin, Content Security Policy, Mixed Content, Service Workers are ignored, given our server-side context.

So changing to `cross-fetch` will do the job AFAICT :)

**Comment by jacktuck** [comment]
@deadcoder0904 Hey no worries! I'll take a look at `cross-fetch` - on first glance, it looks solid.

**Comment by deadcoder0904** [comment]
I tried learning Typescript & replacing with `cross-fetch` but I soon realised lots of code is node-specific. Like you are only fetching till head tag & if we do client side we need to fetch whole html.

So what you need to do for client side thing is like `simple-unfurl` 👇
https://github.com/itaditya/simple-unfurl/blob/master/index.js 

The only thing different in `simple-unfurl` is its incomplete & your schema looks perfect so if you can extract the schema part & combine it like `simple-unfurl` it would be amazing. Thank you for this project. Hope I get to use it someday🤞

I'll find a workaround for my project though. If you are able to do it like `cross-fetch` which works for both node & browser, then it would be awesome ❤️

**Comment by deadcoder0904** [comment]
> Can you explain why this bit is node specific though?

I mean to say that you can't fetch only till head tag in client, you have to fetch everything. Also, you are using `url` from node.

Is there anything else I'm missing you are using from node?

Also do you have a timeframe (maybe estimation) for the browser release?

**Comment by jacktuck** [comment]
> I mean to say that you can't fetch only till head tag in client, you have to fetch everything.
I get what you mean, but unsure as to _why_ that is the case. It still does a GET request rather than HEAD request. It just stops parsing when </head> is reached since no metadata should be found after this point.

> Is there anything else I'm missing you are using from node?
I _think_ that would be it, i guess I need to make the module bundle friendly too, if it isn't already.

> Also do you have a timeframe (maybe estimation) for the browser release?
Good question. I'll try and have something working this week time permitting.

**Comment by deadcoder0904** [comment]
Thank you I'll monkey-patch something till then :)

**Comment by deadcoder0904** [comment]
> I get what you mean, but unsure as to why that is the case. It still does a GET request rather than HEAD request. It just stops parsing when </head> is reached since no metadata should be found after this point.

Oops I saw the code again & I thought `Parser` fetches only till head tag. I completely missed `fetch` fetching the whole thing & then parsing it till `head` 🤣

**Comment by deadcoder0904** [comment]
Friendly ping :) 

Any progress?

**Comment by lucascorrea97** [comment]
Any updates on that?

**Comment by jacktuck** [comment]
Been busy with work i've recently started a new job. I'll look this evening.

**Comment by jacktuck** [comment]
So i've taken an initial look at how much work is involved.

And so far I figure we need to replace fetch with cross-fetch and iconv-lite (or figure out how to make it isomorphic easily, docs are unclear). One interesting thing is node-fetch implemented some non-standard helpers which we made use of like timeouts and size limits. So we need to figure out if those are important and if we can implement it ontop of cross-fetch 😓

**Comment by jacktuck** [comment]
@deadcoder0904 i've had a look at your repo (thanks for making it btw). I have confirmed it works, at least for the domain you're testing. I've done an npm release, which is a major release since it breaks some bits such as timeouts. Checkout `unfurl.js@3.0.0` and let me know how it goes!

**Comment by deadcoder0904** [comment]
No, it's not working - https://codesandbox.io/s/1qx99lo9ml

The error is 

```bash
> ModuleNotFoundError
Could not find module in path: 'unfurl.js/dist/unexpectedError' relative to 
'/node_modules/unfurl.js/dist/index.js'
```

I had a look & its this line https://github.com/jacktuck/unfurl/blob/a0cff1efeb6e1da746fe5c16f59015d6bbadf160/dist/index.js#L18

But, the file is [UnexpectedError.js](https://github.com/jacktuck/unfurl/blob/master/dist/UnexpectedError.js) & required one is `unexpectedError.js`.

It's a typo somewhere 😂

And thanks for doing it 🙌

**Comment by jacktuck** [comment]
@deadcoder0904 Not sure why codesandbox does not work but if you try your repo does it work locally? It does for me.

`cd unfurl-chrome-extension-bug`
`npm i unfurl.js@3.0.0`
then just change the unfurl call to do
```
  _fetchMeta = async () => {
    try {
      let result = await unfurl("https://akshaykadam.me");
      console.log("result", result);
      this.setState({ result });
    } catch (e) {
      console.error("e", e);
    }
  };
```

![image](https://user-images.githubusercontent.com/8209433/52913888-09b9fb00-32ba-11e9-9532-ecc7762a788f.png)

**Comment by jacktuck** [comment]
Looks like that was the case, nice find! I've published 3.0.1 to npm.

**Comment by deadcoder0904** [comment]
Naah still doesn't work for me. Got this error now -

```bash
Refused to set unsafe header "user-agent"
```

Updated code to use Hooks 👉https://github.com/deadcoder0904/unfurl-chrome-extension-bug

<img width="911" alt="bug" src="https://user-images.githubusercontent.com/16436270/52917090-46631200-330d-11e9-8db7-f647af2dfca7.png">

**Comment by deadcoder0904** [comment]
Okay saw your edited comment (please don't edit valuable commits 😂) & I changed the breaking change from

```js
unfurl({
  uri: "https://framer.com"
});
```
to

```js
unfurl("https://framer.com");
```

and it finally works 🎉

Thank you 🙌

**Comment by deadcoder0904** [comment]
But the error

```bash
Refused to set unsafe header "user-agent"
```

is still there. Other than that works fine.

**Comment by jacktuck** [comment]
👍 Will look at that and update the docs at some point

**Comment by deadcoder0904** [comment]
> I think that is error is because you cant set UA header in the browser (as it is not possible)?

Yes, according to https://stackoverflow.com/a/33144144/6141587

So I think https://github.com/jacktuck/unfurl/blob/master/src/index.ts#L50 must be changed.

So instead of doing

```js
const res = await fetch(url, {
    headers: {
      Accept: "text/html, application/xhtml+xml",
      "User-Agent": opts.userAgent
    }
  });
```

I think it shall do

```js
const isBrowser = typeof window !== undefined;
const headers = isBrowser ? {} : {
    Accept: "text/html, application/xhtml+xml",
    "User-Agent": opts.userAgent
};
const res = await fetch(url, {
    headers
  });
```

WDYT? Is it correct? Or are there other places where header is set?

**Comment by deadcoder0904** [comment]
Also, I think the README example can be a little better. It gets confusing to find `unfurl` on `npm` since the package name is `unfurl.js` & there are so many `unfurl` packages on `npm`. And `./unfurl.js` makes it feel like a relative path.

Instead of

```js
const unfurl = require('./unfurl.js')
const result = unfurl('https://github.com/trending')
```

You can probably do

```js
const unfurl = require('unfurl.js')
(async function() {
   const result = await unfurl('https://github.com/trending')
})();
```

**Comment by jacktuck** [comment]
@deadcoder0904 Both of those changes sound good to me. Want to make a PR?

**Comment by deadcoder0904** [comment]
`typeof process !== 'undefined' && process.versions && process.versions.node` is hard to read than `typeof window !== undefined` I guess 🤷‍♂️

**Comment by deadcoder0904** [comment]
I tried doing it but it's failing tests. Maybe it's better for you to make changes & push a version whenever you have time :)

**Comment by ubershmekel** [comment]
I saw this change https://github.com/jacktuck/unfurl/commit/76cab79ec1fbc02e9e3e2e928d224c4c52b8a26b that states browsers won't be supported. Why is that the case?

**Comment by jacktuck** [comment]
@ubershmekel Hi. That was because doing Unfurling in the browser is thwart with issues. Primarily it's unfeasible due to CORS. Which you can get around if you proxy your requests - but at that point you may as well do the unfurl there too (i.e. server side).

**Comment by deadcoder0904** [comment]
> That was because doing Unfurling in the browser is thwart with issues

What issues? Bummer, this was a great use for Chrome Extensions where we don't need server-side.

**Comment by jacktuck** [comment]
#57

**Comment by deadcoder0904** [comment]
Cool, any version that works client-side? Because the schema is rad here 😂
